name: Docker Build Image

on:
  push:
    branches:
      - "main"

env:
    OPENREFINE_VERSION: '3.7.6'
    EXTENSION_URI: https://github.com/MaastrichtU-IDS/ucum-fhir-openrefine-extension/releases/download/v0.1/openrefine-ucum-fhir-grel.zip
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
                      ${{ env.IMAGE_NAME }}:${{ env.OPENREFINE_VERSION }}
                      ${{ env.IMAGE_NAME }}:latest
          build-args: |
                      OPENREFINE_VERSION=${{ env.OPENREFINE_VERSION }}
                      EXTENSION_URI=${{ env.EXTENSION_URI }}

